---
title: "quintile"
author: "Avishek"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, 
                      cache = TRUE, 
                      warning = F,
                      fig.align = "center", 
                      fig.width = 5, 
                      fig.height = 5)
```

# Cluster by quintiles


```{r}
set.seed(2023)
library(dplyr)
library(cluster)
library(ggplot2)
library(factoextra)
library(clusterCrit)
library(clustertend)
library(fpc)
library(clusterSim)

load('../../../data/master_pms_df.Rdata')

# Convert selected columns to numeric
master <- master %>%
  mutate(PMS_DBPOP = as.numeric(gsub(",", "", PMS_DBPOP)), # Dissemination block population
         PMS_DAPOP = as.numeric(gsub(",", "", PMS_DAPOP)), # Dissemination area population
         PMS_CSDPOP = as.numeric(gsub(",", "", PMS_CSDPOP)), # Census subdivision population
         PMS_CMAPOP = as.numeric(gsub(",", "", PMS_CMAPOP)), # Census metropolitan area population
         PMS_PRPOP = as.numeric(gsub(",", "", PMS_PRPOP)), # Province or territory population
         # in_db_emp = as.numeric(in_db_emp),
         # in_db_pharma = as.numeric(in_db_pharma),
         # in_db_childcare = as.numeric(in_db_childcare),
         # in_db_health = as.numeric(in_db_health),
         # in_db_grocery = as.numeric(in_db_grocery),
         # in_db_educpri = as.numeric(in_db_educpri),
         # in_db_educsec = as.numeric(in_db_educsec),
         # in_db_lib = as.numeric(in_db_lib),
         # in_db_parks = as.numeric(in_db_parks),
         # in_db_transit = as.numeric(in_db_transit),
         PMS_prox_idx_emp = as.numeric(PMS_prox_idx_emp),
         PMS_prox_idx_pharma = as.numeric(PMS_prox_idx_pharma),
         PMS_prox_idx_childcare = as.numeric(PMS_prox_idx_childcare),
         PMS_prox_idx_health = as.numeric(PMS_prox_idx_health),
         PMS_prox_idx_grocery = as.numeric(PMS_prox_idx_grocery),
         PMS_prox_idx_educpri = as.numeric(PMS_prox_idx_educpri),
         PMS_prox_idx_educsec = as.numeric(PMS_prox_idx_educsec),
         PMS_prox_idx_lib = as.numeric(PMS_prox_idx_lib),
         PMS_prox_idx_parks = as.numeric(PMS_prox_idx_parks),
         PMS_prox_idx_transit = as.numeric(PMS_prox_idx_transit),
         DBUID = as.character(DBUID),
         PMS_DAUID = as.character(PMS_DAUID),
         PMS_CSDUID = as.character(PMS_CSDUID),
         PMS_CMAUID = as.character(PMS_CMAUID),
         PMS_CMAPUID = as.character(PMS_CMAPUID),
         PMS_PRUID = as.character(PMS_PRUID),
         PMS_suppressed = as.character(PMS_suppressed),
         PMS_transit_na = as.character(PMS_suppressed))


# Subset columns that start with "prox_idx"
amenities <- colnames(master)[grepl("^PMS_prox_idx", colnames(master))]
# master dataset - contains only proximity columns
master_amenities <- master[, amenities]

# subsampling data 
perc = 3 #percentage of data to subsample
subsample = (nrow(master)/100)*perc 
master_sample = master[sample(nrow(master), subsample),]
```


```{r}
#algorithm function --> must return: data with no NAs, cluster assignments
algo = function(dataset, amen_name){
  
  # remove rows with NA values in amen_name column
  dataset <- dataset[complete.cases(dataset[, amen_name]), ]

  # # calculate quintiles
  # quintiles <- cut(dataset[, amen_name], 
  #                  breaks = quantile(dataset[, amen_name], probs = seq(0, 1, 0.2)),
  #                  include.lowest = TRUE)
  # 
  # # adding quintiles in a new column
  # dataset$quintiles <-  as.numeric(quintiles)
  # 
  # # removing na's
  # clust_data = dataset[!is.na(dataset[,"quintiles"]),c(amen_name, "quintiles")]
  # 
  # cutoffs <- tapply(clust_data[, amen_name], clust_data$quintiles, quantile, probs = c(0, 1))
  # 
  # # cut-off viz
  # # data frame with the cutoff values and group information
  # cutoff_data <- data.frame(Group = rownames(cutoffs))
  # cutoff_data$Start <- sapply(cutoffs, function(x) x["0%"])
  # cutoff_data$End <- sapply(cutoffs, function(x) x["100%"])
  
  
  # sort the column
  df_sort <- sort(dataset[, amen_name])

  # number of rows in each group
  row_each_group <- ceiling(length(df_sort) / 5)
  
  # split vector into five groups
  grouped_data <- split(df_sort, rep(1:5, each = row_each_group, length.out = length(df_sort)))
  
  # Apply min and max functions to each group in grouped_data
  min_vals <- sapply(grouped_data, min)
  max_vals <- sapply(grouped_data, max)
  
  # Create dataframe with group number, min value, and max value
  cutoff_data <- data.frame(Group = 1:5, Start = min_vals, End = max_vals)
  
  # Create vector of group numbers
  group_no <- rep(1:5, each = row_each_group, length.out = length(df_sort))
  
  df_sort = data.frame(df_sort)
  colnames(df_sort) <- "data"
  
  # Add group number as new column in df_sort dataframe
  df_sort$cluster_no <- group_no


  # # Calculate the number of data points in each group
  # group_counts <- table(clust_data$quintiles)
  # 
  # # Add the counts to the cutoff_data dataframe
  # cutoff_data$Count <- group_counts
  # 
  # print(table(cutoff_data$Count))
  
  end_values <- as.vector(cutoff_data$End)
  end_values <- end_values[-length(end_values)]
  
  # # vector of colors for each group
  # cluster_colors <- c("1" = "red", "2" = "blue", "3" = "green", "4" = "purple", "5" = "orange")
  # 

  # plot(ggplot(cutoff_data) +
  #   geom_rect(aes(xmin = Start, xmax = End, ymin = 0, ymax = 0.1, fill = Group)) +
  #   scale_fill_manual(values = cluster_colors) +
  #   labs(x = amen_name, y = NULL,
  #        title = "Cutoff Values by Quartile") +
  #   theme_minimal() +
  #   theme(axis.text.y = element_blank(),
  #         axis.ticks.y = element_blank()) +
  #   coord_cartesian(xlim = range(cutoff_data$Start, cutoff_data$End)))
  
  
  # silhouette plot
  clusts <- df_sort$cluster_no
  comp_data <- df_sort[, "data"]

  sil = silhouette(clusts, dist(comp_data))
  plot(fviz_silhouette(sil))

  avg_sil_width <- mean(sil[, "sil_width"])

  dunn_stats <- cluster.stats(dist(comp_data), clusts)

  xie_beni <- intCriteria(as.matrix(comp_data),
                          as.integer(clusts),
                          'Xie_Beni')$xie_beni

  calinski_harabasz <- calinhara(comp_data, clusts)

  davies_bouldin <- index.DB(comp_data, clusts)
  
  
  return(list(
    'avg_sill_width' = avg_sil_width,
    "dunn_index" = dunn_stats$dunn,
    "xie_beni" = xie_beni,
    "calinski_harabasz" = calinski_harabasz,
    "davies_bouldin" = davies_bouldin$DB,
    'cut_offs' = end_values,
    "cut_data" = cutoff_data)
    )
}
```


### Employment 

```{r}
res_emp = algo(master_sample, "PMS_prox_idx_emp")
```


### Health 

```{r}
res_health = algo(master_sample, "PMS_prox_idx_health")
```

### Childcare 

```{r}
res_childcare = algo(master_sample, "PMS_prox_idx_childcare")
```


### Parks 

```{r}
res_parks = algo(master_sample, "PMS_prox_idx_parks")
```


### Education Primary 

```{r}
res_educpri = algo(master_sample, "PMS_prox_idx_educpri")
```

### Transit 

```{r}
res_transit = algo(master_sample, "PMS_prox_idx_transit")
```

### Pharma 

```{r}
res_pharma = algo(master_sample, "PMS_prox_idx_pharma")
```

### Education Secondary 

```{r}
res_educsec = algo(master_sample, "PMS_prox_idx_educsec")
```

### Grocery 

```{r}
res_grocery = algo(master_sample, "PMS_prox_idx_grocery")
```

### Library 

```{r}
res_lib = algo(master_sample, "PMS_prox_idx_lib")
```


<!--
"PMS_prox_idx_emp", "PMS_prox_idx_pharma", "PMS_prox_idx_childcare", "PMS_prox_idx_health", "PMS_prox_idx_grocery", "PMS_prox_idx_educpri", "PMS_prox_idx_educsec", "PMS_prox_idx_lib", "PMS_prox_idx_parks", "PMS_prox_idx_transit"
-->


```{r}
print("Silhouette Coefficients")
sill_quintiles <- c(res_emp$avg_sill_width, res_pharma$avg_sill_width, res_childcare$avg_sill_width, res_health$avg_sill_width, res_grocery$avg_sill_width, res_educpri$avg_sill_width, res_educsec$avg_sill_width, res_lib$avg_sill_width, res_parks$avg_sill_width, res_transit$avg_sill_width)
sill_quintiles
```

```{r}
print("Dunn Index")
dunn_quintiles <- c(res_emp$dunn_index, res_pharma$dunn_index, res_childcare$dunn_index, res_health$dunn_index, res_grocery$dunn_index, res_educpri$dunn_index, res_educsec$dunn_index, res_lib$dunn_index, res_parks$dunn_index, res_transit$dunn_index)
dunn_quintiles
```
  
  
```{r}
print("Xie Beni")
xie_beni_quintiles <- c(res_emp$xie_beni, res_pharma$xie_beni, res_childcare$xie_beni, res_health$xie_beni, res_grocery$xie_beni, res_educpri$xie_beni, res_educsec$xie_beni, res_lib$xie_beni, res_parks$xie_beni, res_transit$xie_beni)
xie_beni_quintiles
```

```{r}
print("Calinski Harabasz")
calinski_harabasz_quintiles <- c(res_emp$calinski_harabasz, res_pharma$calinski_harabasz, res_childcare$calinski_harabasz, res_health$calinski_harabasz, res_grocery$calinski_harabasz, res_educpri$calinski_harabasz, res_educsec$calinski_harabasz, res_lib$calinski_harabasz, res_parks$calinski_harabasz, res_transit$calinski_harabasz)
calinski_harabasz_quintiles
```

```{r}
print("Davies Bouldin")
davies_bouldin_quintiles <- c(res_emp$davies_bouldin, res_pharma$davies_bouldin, res_childcare$davies_bouldin, res_health$davies_bouldin, res_grocery$davies_bouldin, res_educpri$davies_bouldin, res_educsec$davies_bouldin, res_lib$davies_bouldin, res_parks$davies_bouldin, res_transit$davies_bouldin)
davies_bouldin_quintiles
```


### Cut-offs

```{r}
cut_offs_quintiles <- list(PMS_prox_idx_emp = c(res_emp$cut_offs), 
                           PMS_prox_idx_pharma = c(res_pharma$cut_offs), 
                           PMS_prox_idx_childcare = c(res_childcare$cut_offs), 
                           PMS_prox_idx_health = c(res_health$cut_offs), 
                           PMS_prox_idx_grocery = c(res_grocery$cut_offs), 
                           PMS_prox_idx_educpri = c(res_educpri$cut_offs), 
                           PMS_prox_idx_educsec = c(res_educsec$cut_offs), 
                           PMS_prox_idx_lib = c(res_lib$cut_offs), 
                           PMS_prox_idx_parks = c(res_parks$cut_offs), 
                           PMS_prox_idx_transit = c(res_transit$cut_offs)
                           )
cut_offs_quintiles
```


```{r eval=FALSE}
cut_offs_quintiles <- list(PMS_prox_idx_emp = c(-6.377127, -4.919881, -3.540459, -0.320343), 
                           PMS_prox_idx_pharma = c(-4.26158048, -3.60453831, -2.92062480, -0.01338924), 
                           PMS_prox_idx_childcare = c(-3.872802, -3.013896, -2.321768, -0.081427), 
                           PMS_prox_idx_health = c( -6.1192979, -5.1328029, -4.1930605, -0.3902317), 
                           PMS_prox_idx_grocery = c(-3.6156290, -3.1212955, -2.4522459, -0.2519289), 
                           PMS_prox_idx_educpri = c(-3.0098312, -2.4001979, -1.8643302, -0.2927616), 
                           PMS_prox_idx_educsec = c(-3.0944482, -2.6050425, -2.0612088, -0.1750679), 
                           PMS_prox_idx_lib = c(-2.8100829, -2.4961698, -2.0166546, -0.1421398), 
                           PMS_prox_idx_parks = c(-3.6730061, -3.0220762, -2.3957975, -0.1935847), 
                           PMS_prox_idx_transit = c(-5.3816990, -4.5469013, -3.7507549, -0.5215496)
                           )
cut_offs_quintiles
```

<!--

```{r}
master_sample <- master_sample[complete.cases(master_sample[, "PMS_prox_idx_emp"]), ]

# calculate quintiles
quintiles <- cut(master_sample[, "PMS_prox_idx_emp"], 
                 breaks = c(0, 0.012, 0.021, 0.036, 0.069, 1),
                 labels = c(1, 2, 3, 4, 5)
)

master_sample$quintiles <- as.numeric(quintiles)


emp <- na.omit(master_sample[, c("quintiles")])
clust_data = master_sample[!is.na(master_sample[,"quintiles"]),c("PMS_prox_idx_emp", "quintiles")]
```


```{r}
# sort the column
master_amenities_emp <- sort((master_amenities$PMS_prox_idx_emp))

# number of rows in each group
row_each_group <- ceiling(length(master_amenities_emp) / 5)

# split vector into five groups
grouped_data <- split(master_amenities_emp, rep(1:5, each = row_each_group, length.out = length(master_amenities_emp)))

```

```{r}
# Create vector of group numbers
group_no <- rep(1:5, each = row_each_group, length.out = length(master_amenities_emp))

# Add group number as new column in df_sort dataframe
master_amenities_emp$group_no <- group_no
```

```{r}
master_amenities_emp$group_no
```


```{r}
# Apply min and max functions to each group in grouped_data
min_vals <- sapply(grouped_data, min)
max_vals <- sapply(grouped_data, max)

# Create dataframe with group number, min value, and max value
group_min_max_df <- data.frame(group_no = 1:5, min_val = min_vals, max_val = max_vals)

```

```{r}
group_min_max_df
```

```{r}
# Print the dataframe
cat("1", length(grouped_data[[1]]))
# print(grouped_data[[1]])
print(grouped_data[[1]][1])
print(grouped_data[[1]][84721])
cat("2", length(grouped_data[[2]]))
print(grouped_data[[2]][1])
print(grouped_data[[2]][84721])
cat("3", length(grouped_data[[3]]))
print(grouped_data[[3]][1])
print(grouped_data[[3]][84721])
cat("4", length(grouped_data[[4]]))
print(grouped_data[[4]][1])
print(grouped_data[[4]][84721])
cat("5", length(grouped_data[[5]]))
print(grouped_data[[5]][1])
print(grouped_data[[5]][84718])

```


```{r}
# Sample data
column_data <- c(10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65)

# Split column into 5 equal groups
groups <- cut(column_data, breaks = 5, labels = FALSE, include.lowest = TRUE)

# Calculate group statistics
group_stats <- tapply(column_data, groups, function(x) {
  data_points <- length(x)
  start_value <- min(x)
  end_value <- max(x)
  data.frame(Data_Points = data_points, Start_Value = start_value, End_Value = end_value)
})

# Combine group statistics into a dataframe
group_df <- do.call(rbind, group_stats)

# Add Group No. column
group_df$Group_No <- seq_len(nrow(group_df))

# Print the dataframe
print(group_df)

```

```{r}
cutoff_data
```


```{r}
# cutoffs <- tapply(clust_data$PMS_prox_idx_emp, clust_data$quintiles, quantile, probs = c(0, 0.25, 0.5, 0.75, 1))
cutoffs <- tapply(clust_data$PMS_prox_idx_emp, clust_data$quintiles, quantile, probs = c(0, 1))
```

```{r}
cutoffs
```

```{r}
min(clust_data$PMS_prox_idx_emp)
```


```{r}
cutoff_data <- data.frame(Group = rownames(cutoffs))
cutoff_data$Start <- sapply(cutoffs, function(x) x["0%"])
cutoff_data$End <- sapply(cutoffs, function(x) x["100%"])


cluster_colors <- c("1" = "red", "2" = "blue", "3" = "green", "4" = "purple", "5" = "orange")

ggplot(cutoff_data) +
  
  geom_rect(aes(xmin = Start, xmax = End, ymin = 0, ymax = 0.1, fill = Group)) +
  scale_fill_manual(values = cluster_colors) +
  labs(x = "PMS_prox_idx_emp", y = NULL,
       title = "Cutoff Values by Quartile") +
  theme_minimal() +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank()) +
  coord_cartesian(xlim = range(cutoff_data$Start, cutoff_data$End))
```


```{r}
# silhouette plot
clusts_log <- clust_data$quintiles

comp_data_log <- clust_data$PMS_prox_idx_emp

sil_log = silhouette(clusts_log, dist(comp_data_log))
plot(fviz_silhouette(sil_log))
```

```{r}
# dunn index - a higher dunn index indicate better clustering
dunn_stats <- cluster.stats(dist(comp_data_log), clusts_log)
dunn_stats$dunn
```


```{r}
dunn_stats
```


```{r}
avg_sil_width <- mean(sil_log[, "sil_width"])

print(round(avg_sil_width,2))
```

```{r}
calinski_harabasz <- calinhara(comp_data_log,clusts_log)
calinski_harabasz
```

```{r}
xie_beni <- intCriteria(as.matrix(comp_data_log), 
                          as.integer(clusts_log), 
                          'Xie_Beni')$xie_beni
xie_beni
```

```{r}
library(clusterSim)
davies_bouldin <- index.DB(comp_data_log, clusts_log)
davies_bouldin$DB
```


-->
